/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillIdRouteImport } from './routes/skill.$id'
import { Route as AuthorUsernameRouteImport } from './routes/author.$username'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillIdRoute = SkillIdRouteImport.update({
  id: '/skill/$id',
  path: '/skill/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorUsernameRoute = AuthorUsernameRouteImport.update({
  id: '/author/$username',
  path: '/author/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/author/$username': typeof AuthorUsernameRoute
  '/skill/$id': typeof SkillIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/author/$username': typeof AuthorUsernameRoute
  '/skill/$id': typeof SkillIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/author/$username': typeof AuthorUsernameRoute
  '/skill/$id': typeof SkillIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/login' | '/author/$username' | '/skill/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/login' | '/author/$username' | '/skill/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/author/$username'
    | '/skill/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  AuthorUsernameRoute: typeof AuthorUsernameRoute
  SkillIdRoute: typeof SkillIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill/$id': {
      id: '/skill/$id'
      path: '/skill/$id'
      fullPath: '/skill/$id'
      preLoaderRoute: typeof SkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/$username': {
      id: '/author/$username'
      path: '/author/$username'
      fullPath: '/author/$username'
      preLoaderRoute: typeof AuthorUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  AuthorUsernameRoute: AuthorUsernameRoute,
  SkillIdRoute: SkillIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
